#!/bin/bash
echo "Linux Build Bootstrap!"

# Stop on first error
set -e

SCRIPTS_DIR=$(dirname "$0")
REPO_DIR=$SCRIPTS_DIR/../..
SOURCE_DIR=$REPO_DIR/Source

SOUP_DIR=$REPO_DIR/out/run/
SOUP=$SOUP_DIR/soup
GENERATE=$SOUP_DIR/generate

SOUP_PACKAGES_DIR=/home/mwasplund/.soup/packages

BOOTSTRAP='dotnet run --project $SOURCE_DIR/GenerateSharp/BootstrapBuild/'

# sudo apt install build-essentials
# sudo apt install clang
# sudo apt install dotnet-sdk-8.0

eval $SOUP restore $SOURCE_DIR/client/cli/

eval $GENERATE $SOUP_PACKAGES_DIR/Wren/mwasplund/Soup.Build.Utils/0.7.0/out/tsWW3RZ_9Jb7Xbk2kTzx3n6uQUM/.soup/
eval $BOOTSTRAP $SOUP_PACKAGES_DIR/Wren/mwasplund/Soup.Build.Utils/0.7.0/out/tsWW3RZ_9Jb7Xbk2kTzx3n6uQUM/.soup/

eval $GENERATE $SOUP_PACKAGES_DIR/Wren/Soup/Cpp.Compiler/0.11.0/out/tsWW3RZ_9Jb7Xbk2kTzx3n6uQUM/.soup/
eval $BOOTSTRAP $SOUP_PACKAGES_DIR/Wren/Soup/Cpp.Compiler/0.11.0/out/tsWW3RZ_9Jb7Xbk2kTzx3n6uQUM/.soup/

eval $GENERATE $SOUP_PACKAGES_DIR/Wren/Soup/Cpp.Compiler.Clang/0.3.2/out/tsWW3RZ_9Jb7Xbk2kTzx3n6uQUM/.soup/
eval $BOOTSTRAP $SOUP_PACKAGES_DIR/Wren/Soup/Cpp.Compiler.Clang/0.3.2/out/tsWW3RZ_9Jb7Xbk2kTzx3n6uQUM/.soup/

eval $GENERATE $SOUP_PACKAGES_DIR/Wren/Soup/Cpp.Compiler.GCC/0.4.0/out/tsWW3RZ_9Jb7Xbk2kTzx3n6uQUM/.soup/
eval $BOOTSTRAP $SOUP_PACKAGES_DIR/Wren/Soup/Cpp.Compiler.GCC/0.4.0/out/tsWW3RZ_9Jb7Xbk2kTzx3n6uQUM/.soup/

eval $GENERATE $SOUP_PACKAGES_DIR/Wren/Soup/Cpp.Compiler.MSVC/0.10.0/out/tsWW3RZ_9Jb7Xbk2kTzx3n6uQUM/.soup/
eval $BOOTSTRAP $SOUP_PACKAGES_DIR/Wren/Soup/Cpp.Compiler.MSVC/0.10.0/out/tsWW3RZ_9Jb7Xbk2kTzx3n6uQUM/.soup/

eval $GENERATE $SOUP_PACKAGES_DIR/Wren/Soup/Cpp/0.12.0/out/tsWW3RZ_9Jb7Xbk2kTzx3n6uQUM/.soup/
eval $BOOTSTRAP $SOUP_PACKAGES_DIR/Wren/Soup/Cpp/0.12.0/out/tsWW3RZ_9Jb7Xbk2kTzx3n6uQUM/.soup/

eval $SOUP build $SOUP_PACKAGES_DIR/Wren/Soup/Cpp/0.12.0/ -force -flavor Release

eval $SOUP build $SOUP_PACKAGES_DIR/Cpp/mwasplund/Opal/0.11.0/ -skipEvaluate -v:d
eval $GENERATE $SOUP_PACKAGES_DIR/Cpp/mwasplund/Opal/0.11.0/out/J_HqSstV55vlb-x6RWC_hLRFRDU/.soup/
eval $BOOTSTRAP $SOUP_PACKAGES_DIR/Cpp/mwasplund/Opal/0.11.0/out/J_HqSstV55vlb-x6RWC_hLRFRDU/.soup/

echo "Finished"