#!/bin/bash
echo "Linux Build Client: $1"

# Stop on first error
set -e

FLAVOR="$1"
SCRIPTS_DIR=$(dirname "$0")

ROOT_DIR=$SCRIPTS_DIR/../..
SOURCE_DIR=$ROOT_DIR/Source
OUTPUT_DIR=$ROOT_DIR/out
CLIENT_CLI_DIR=$SOURCE_DIR/Client/CLI

# Build the client
echo soup build $CLIENT_CLI_DIR -flavor $FLAVOR
eval soup build $CLIENT_CLI_DIR -flavor $FLAVOR