#!/bin/bash
echo "Linux Build: $1"

# Stop on first error
set -e

FLAVOR="$1"
SCRIPTS_DIR=$(dirname "$0")

# Build Client
# echo $SCRIPTS_DIR/build-client
# eval $SCRIPTS_DIR/build-client
echo $SCRIPTS_DIR/soup build Source/Client/CLI -flavor $FLAVOR
eval $SCRIPTS_DIR/soup build Source/Client/CLI -flavor $FLAVOR

# Build SWhere tool
echo $SCRIPTS_DIR/build-swhere
eval $SCRIPTS_DIR/build-swhere

# Build PackageManager
echo $SCRIPTS_DIR/build-packagemanager
eval $SCRIPTS_DIR/build-packagemanager