#!/bin/bash
echo "Linux Build SoupView!"

# Stop on first error
set -e

FLAVOR="$1"
SCRIPTS_DIR=$(dirname "$0")
CODE_DIR=$SCRIPTS_DIR/../../code
SWHERE_DIR=$CODE_DIR/generate-sharp/soup-view

# Build SWhere tool
echo dotnet publish $SWHERE_DIR -c $FLAVOR -r linux-x64 --self-contained
eval dotnet publish $SWHERE_DIR -c $FLAVOR -r linux-x64 --self-contained
