#!/bin/bash
echo "Linux Build!"

# Stop on first error
set -e

SCRIPTS_DIR=$(dirname "$0")

# Build Client
echo $SCRIPTS_DIR/build-client
eval $SCRIPTS_DIR/build-client

# Build BuiltIns
echo $SCRIPTS_DIR/build-builtins
eval $SCRIPTS_DIR/build-builtins

# Build SWhere tool
echo $SCRIPTS_DIR/build-swhere
eval $SCRIPTS_DIR/build-swhere

# Build PackageManager
echo $SCRIPTS_DIR/build-packagemanager
eval $SCRIPTS_DIR/build-packagemanager