#!/bin/bash
echo "Linux Build PackageManager!"

OUT_DIR=~/repos/Soup/out

# Stop on first error
set -e

SCRIPTS_DIR=$(dirname "$0")
SOURCE_DIR=$SCRIPTS_DIR/../../Source
PACKAGE_MANAGER_DIR=$SOURCE_DIR/GenerateSharp/PackageManager

# Build PackageManager
echo dotnet publish $PACKAGE_MANAGER_DIR -c Release -r linux-x64 --self-contained
eval dotnet publish $PACKAGE_MANAGER_DIR -c Release -r linux-x64 --self-contained
