#!/bin/bash
echo "Linux Build Client: $1"

# Stop on first error
set -e

FLAVOR="$1"
SCRIPTS_DIR=$(dirname "$0")

ROOT_DIR=$SCRIPTS_DIR/../..
SOURCE_DIR=$ROOT_DIR/Source
OUTPUT_DIR=$ROOT_DIR/out
CLIENT_CLI_DIR=$SOURCE_DIR/Client/CLI
MONITOR_CLIENT_DIR=$SOURCE_DIR/Monitor/Client

# Build each version of the monitor client dll
echo soup build $MONITOR_CLIENT_DIR -architecture x64 -flavor $FLAVOR
eval soupd build $MONITOR_CLIENT_DIR -architecture x64 -flavor $FLAVOR

echo soup build $MONITOR_CLIENT_DIR -architecture x86 -flavor $FLAVOR
eval soupd build $MONITOR_CLIENT_DIR -architecture x86 -flavor $FLAVOR

# Build the client
echo soup build $CLIENT_CLI_DIR -flavor $FLAVOR
eval soupd build $CLIENT_CLI_DIR -flavor $FLAVOR

# Get the targets
ClientCLIOutputDirectory=$(soupd target $CLIENT_CLI_DIR -flavor $FLAVOR)
MonitorClientOutputX64Directory=$(soupd target $MONITOR_CLIENT_DIR -architecture x64 -flavor $FLAVOR)
MonitorClientOutputX86Directory=$(soupd target $MONITOR_CLIENT_DIR -architecture x86 -flavor $FLAVOR)

# Copy the monitor client dlls
echo cp "$MonitorClientOutputX64Directory/bin/Monitor.Client.so" "$ClientCLIOutputDirectory/bin/Monitor.Client.64.so"
cp "$MonitorClientOutputX64Directory/bin/Monitor.Client.so" "$ClientCLIOutputDirectory/bin/Monitor.Client.64.so"
echo cp "$MonitorClientOutputX86Directory/bin/Monitor.Client.so" "$ClientCLIOutputDirectory/bin/Monitor.Client.32.so"
cp "$MonitorClientOutputX86Directory/bin/Monitor.Client.so" "$ClientCLIOutputDirectory/bin/Monitor.Client.32.so"