#!/bin/bash

# Stop on first error
set -e

SCRIPTS_DIR=$(dirname "$0")
ROOT_DIR=$SCRIPTS_DIR/../..
OUT_DIR=$ROOT_DIR/out
RUN_DIR=$OUT_DIR/run

# Cleanup previous runs
tar -a -cf $OUT_DIR/soup-build-0.35.4-linux-x64.tar.gz -C $RUN_DIR .