#pragma once 

namespace Monitor
{
	export class IDetourCallback
	{
	public:
		virtual void OnShutdown() = 0;
		virtual void OnError(std::string_view message) = 0;

		// FileApi
		virtual void OnAreFileApisANSI(bool result) = 0;
		virtual void OnCompareFileTime(int32_t result) = 0;
		virtual void OnCreateDirectoryA(std::string_view pathName, bool result) = 0;
		virtual void OnCreateDirectoryW(std::wstring_view pathName, bool result) = 0;
		virtual void OnCreateFile2(std::wstring_view fileName, uint32_t desiredAccess, uint32_t sharedMode, uint32_t creationDisposition) = 0;
		virtual void OnCreateFileA(std::string_view fileName, uint32_t desiredAccess, uint32_t sharedMode, uint32_t creationDisposition, uint32_t flagsAndAttributes) = 0;
		virtual void OnCreateFileW(std::wstring_view fileName, uint32_t desiredAccess, uint32_t sharedMode, uint32_t creationDisposition, uint32_t flagsAndAttributes) = 0;
		virtual void OnDefineDosDeviceW(uint32_t flags, std::wstring_view deviceName, std::wstring_view targetPath, bool result) = 0;
		virtual void OnDeleteFileA(std::string_view fileName, bool result) = 0;
		virtual void OnDeleteFileW(std::wstring_view fileName, bool result) = 0;
		virtual void OnDeleteVolumeMountPointW(std::wstring_view volumeMountPoint, bool result) = 0;
		virtual void OnFileTimeToLocalFileTime(bool result) = 0;
		virtual void OnFindClose(bool result) = 0;
		virtual void OnFindCloseChangeNotification(bool result) = 0;
		virtual void OnFindFirstChangeNotificationA(std::string_view pathName, bool watchSubtree, uint32_t notifyFilter) = 0;
		virtual void OnFindFirstChangeNotificationW(std::wstring_view pathName, bool watchSubtree, uint32_t notifyFilter) = 0;
		virtual void OnFindFirstFileA(std::string_view fileName) = 0;
		virtual void OnFindFirstFileW(std::wstring_view fileName) = 0;
		virtual void OnFindFirstFileExA(std::string_view fileName) = 0;
		virtual void OnFindFirstFileExW(std::wstring_view fileName) = 0;
		virtual void OnFindFirstFileNameW(std::wstring_view fileName, uint32_t flags) = 0;
		virtual void OnFindFirstStreamW(std::wstring_view fileName) = 0;
		virtual void OnFindFirstVolumeW(std::wstring_view fileName) = 0;
		virtual void OnFindNextChangeNotification(bool result) = 0;
		virtual void OnFindNextFileA(bool result) = 0;
		virtual void OnFindNextFileW(bool result) = 0;
		virtual void OnFindNextFileNameW(bool result) = 0;
		virtual void OnFindNextStreamW(bool result) = 0;
		virtual void OnFindNextVolumeW(bool result) = 0;
		virtual void OnFindVolumeClose(bool result) = 0;
		virtual void OnFlushFileBuffers(bool result) = 0;
		virtual void OnGetCompressedFileSizeA(std::string_view fileName, uint32_t result) = 0;
		virtual void OnGetCompressedFileSizeW(std::wstring_view fileName, uint32_t result) = 0;
		virtual void OnGetDiskFreeSpaceA(std::string_view rootPathName, bool result) = 0;
		virtual void OnGetDiskFreeSpaceW(std::wstring_view rootPathName, bool result) = 0;
		virtual void OnGetDiskFreeSpaceExA(std::string_view directoryName, bool result) = 0;
		virtual void OnGetDiskFreeSpaceExW(std::wstring_view directoryName, bool result) = 0;
		virtual void OnGetDriveTypeA(std::string_view rootPathName, uint32_t result) = 0;
		virtual void OnGetDriveTypeW(std::wstring_view rootPathName, uint32_t result) = 0;
		virtual void OnGetFileAttributesA(std::string_view fileName, uint32_t result) = 0;
		virtual void OnGetFileAttributesW(std::wstring_view fileName, uint32_t result) = 0;
		virtual void OnGetFileAttributesExA(std::string_view fileName, bool result) = 0;
		virtual void OnGetFileAttributesExW(std::wstring_view fileName, bool result) = 0;
		virtual void OnGetFileInformationByHandle(bool result) = 0;
		virtual void OnGetFileSize(uint32_t result) = 0;
		virtual void OnGetFileSizeEx(uint32_t result) = 0;
		virtual void OnGetFileTime(bool result) = 0;
		virtual void OnGetFileType(uint32_t result) = 0;
		virtual void OnGetFinalPathNameByHandleA(uint32_t result) = 0;
		virtual void OnGetFinalPathNameByHandleW(uint32_t result) = 0;
		virtual void OnGetFullPathNameA(std::string_view fileName, uint32_t result) = 0;
		virtual void OnGetFullPathNameW(std::wstring_view fileName, uint32_t result) = 0;
		virtual void OnGetLogicalDrives(uint32_t result) = 0;
		virtual void OnGetLogicalDriveStringsW(std::wstring_view buffer, uint32_t result) = 0;
		virtual void OnGetLongPathNameA(std::string_view shortPath, std::string_view longPath, uint32_t result) = 0;
		virtual void OnGetLongPathNameW(std::wstring_view shortPath, std::wstring_view longPath, uint32_t result) = 0;
		virtual void OnGetShortPathNameW(std::wstring_view longPath, std::wstring_view shortPath, uint32_t result) = 0;
		virtual void OnGetTempFileNameA(std::string_view pathName, std::string_view prefixString, uint32_t unique, std::string_view tempFileName, uint32_t result) = 0;
		virtual void OnGetTempFileNameW(std::wstring_view pathName, std::wstring_view prefixString, uint32_t unique, std::wstring_view tempFileName, uint32_t result) = 0;
		virtual void OnGetTempPathA(std::string_view buffer, uint32_t result) = 0;
		virtual void OnGetTempPathW(std::wstring_view buffer, uint32_t result) = 0;
		virtual void OnGetVolumeInformationA(bool result) = 0;
		virtual void OnGetVolumeInformationW(bool result) = 0;
		virtual void OnGetVolumeInformationByHandleW(bool result) = 0;
		virtual void OnGetVolumeNameForVolumeMountPointW(bool result) = 0;
		virtual void OnGetVolumePathNamesForVolumeNameW(bool result) = 0;
		virtual void OnGetVolumePathNameW(std::wstring_view filename, bool result) = 0;
		virtual void OnLocalFileTimeToFileTime(bool result) = 0;
		virtual void OnLockFile(bool result) = 0;
		virtual void OnLockFileEx(bool result) = 0;
		virtual void OnQueryDosDeviceW(std::wstring_view deviceName, uint32_t result) = 0;
		virtual void OnReadFile(bool result) = 0;
		virtual void OnReadFileEx(bool result) = 0;
		virtual void OnReadFileScatter(bool result) = 0;
		virtual void OnRemoveDirectoryA(std::string_view pathName, bool result) = 0;
		virtual void OnRemoveDirectoryW(std::wstring_view pathName, bool result) = 0;
		virtual void OnSetEndOfFile(bool result) = 0;
		virtual void OnSetFileApisToANSI() = 0;
		virtual void OnSetFileApisToOEM() = 0;
		virtual void OnSetFileAttributesA(std::string_view fileName, bool result) = 0;
		virtual void OnSetFileAttributesW(std::wstring_view fileName, bool result) = 0;
		virtual void OnSetFileInformationByHandle(bool result) = 0;
		virtual void OnSetFileIoOverlappedRange(bool result) = 0;
		virtual void OnSetFilePointer(uint32_t result) = 0;
		virtual void OnSetFilePointerEx(bool result) = 0;
		virtual void OnSetFileTime(bool result) = 0;
		virtual void OnSetFileValidData(bool result) = 0;
		virtual void OnUnlockFile(bool result) = 0;
		virtual void OnUnlockFileEx(bool result) = 0;
		virtual void OnWriteFile(bool result) = 0;
		virtual void OnWriteFileEx(bool result) = 0;
		virtual void OnWriteFileGather(bool result) = 0;

		// LibLoaderApi
		virtual void OnLoadLibraryA() = 0;
		virtual void OnLoadLibraryW() = 0;
		virtual void OnLoadLibraryExA() = 0;
		virtual void OnLoadLibraryExW(std::wstring_view libFileName) = 0;

		// ProcessEnv
		virtual void OnSearchPathA() = 0;
		virtual void OnSearchPathW() = 0;

		// ProcessThreadsApi
		virtual void OnCreateProcessA() = 0;
		virtual void OnCreateProcessW() = 0;
		virtual void OnCreateProcessAsUserA() = 0;
		virtual void OnCreateProcessAsUserW() = 0;
		virtual void OnExitProcess() = 0;

		// UndocumentedApi
		virtual void OnPrivCopyFileExA() = 0;
		virtual void OnPrivCopyFileExW() = 0;

		// WinBase
		virtual void OnCopyFileA() = 0;
		virtual void OnCopyFileW() = 0;
		virtual void OnCopyFile2() = 0;
		virtual void OnCopyFileExA() = 0;
		virtual void OnCopyFileExW() = 0;
		virtual void OnCopyFileTransactedA() = 0;
		virtual void OnCopyFileTransactedW() = 0;
		virtual void OnCreateDirectoryExA() = 0;
		virtual void OnCreateDirectoryExW() = 0;
		virtual void OnCreateDirectoryTransactedA() = 0;
		virtual void OnCreateDirectoryTransactedW() = 0;
		virtual void OnCreateFileTransactedA() = 0;
		virtual void OnCreateFileTransactedW() = 0;
		virtual void OnCreateHardLinkA() = 0;
		virtual void OnCreateHardLinkW() = 0;
		virtual void OnCreateHardLinkTransactedA() = 0;
		virtual void OnCreateHardLinkTransactedW() = 0;
		virtual void OnCreateProcessWithLogonW() = 0;
		virtual void OnCreateProcessWithTokenW() = 0;
		virtual void OnCreateSymbolicLinkA() = 0;
		virtual void OnCreateSymbolicLinkW() = 0;
		virtual void OnCreateSymbolicLinkTransactedA() = 0;
		virtual void OnCreateSymbolicLinkTransactedW() = 0;
		virtual void OnDecryptFileA() = 0;
		virtual void OnDecryptFileW() = 0;
		virtual void OnDeleteFileTransactedA() = 0;
		virtual void OnDeleteFileTransactedW() = 0;
		virtual void OnEncryptFileA() = 0;
		virtual void OnEncryptFileW() = 0;
		virtual void OnFileEncryptionStatusA() = 0;
		virtual void OnFileEncryptionStatusW() = 0;
		virtual void OnFindFirstFileNameTransactedW() = 0;
		virtual void OnFindFirstFileTransactedA() = 0;
		virtual void OnFindFirstFileTransactedW() = 0;
		virtual void OnFindFirstStreamTransactedW() = 0;
		virtual void OnGetBinaryTypeA() = 0;
		virtual void OnGetBinaryTypeW() = 0;
		virtual void OnGetCompressedFileSizeTransactedA() = 0;
		virtual void OnGetCompressedFileSizeTransactedW() = 0;
		virtual void OnGetDllDirectoryA() = 0;
		virtual void OnGetDllDirectoryW() = 0;
		virtual void OnGetFileAttributesTransactedA() = 0;
		virtual void OnGetFileAttributesTransactedW() = 0;
		virtual void OnGetFileBandwidthReservation() = 0;
		virtual void OnGetFileInformationByHandleEx() = 0;
		virtual void OnGetFileSecurityA() = 0;
		virtual void OnGetFullPathNameTransactedA() = 0;
		virtual void OnGetFullPathNameTransactedW() = 0;
		virtual void OnGetLongPathNameTransactedA() = 0;
		virtual void OnGetLongPathNameTransactedW() = 0;
		virtual void OnGetQueuedCompletionStatus() = 0;
		virtual void OnGetQueuedCompletionStatusEx() = 0;
		virtual void OnGetShortPathNameA() = 0;
		virtual void OnLoadModule() = 0;
		virtual void OnLoadPackagedLibrary() = 0;
		virtual void OnMoveFileA() = 0;
		virtual void OnMoveFileW() = 0;
		virtual void OnMoveFileExA() = 0;
		virtual void OnMoveFileExW() = 0;
		virtual void OnMoveFileTransactedA() = 0;
		virtual void OnMoveFileTransactedW() = 0;
		virtual void OnMoveFileWithProgressA() = 0;
		virtual void OnMoveFileWithProgressW() = 0;
		virtual void OnOpenEncryptedFileRawA() = 0;
		virtual void OnOpenEncryptedFileRawW() = 0;
		virtual void OnOpenFile() = 0;
		virtual void OnOpenFileById() = 0;
		virtual void OnReadEncryptedFileRaw() = 0;
		virtual void OnRemoveDirectoryTransactedA() = 0;
		virtual void OnRemoveDirectoryTransactedW() = 0;
		virtual void OnReOpenFile() = 0;
		virtual void OnReplaceFileA() = 0;
		virtual void OnReplaceFileW() = 0;
		virtual void OnSetCurrentDirectoryA() = 0;
		virtual void OnSetCurrentDirectoryW() = 0;
		virtual void OnSetDllDirectoryA() = 0;
		virtual void OnSetDllDirectoryW() = 0;
		virtual void OnSetFileAttributesTransactedA() = 0;
		virtual void OnSetFileAttributesTransactedW() = 0;
		virtual void OnSetFileBandwidthReservation() = 0;
		virtual void OnSetFileCompletionNotificationModes() = 0;
		virtual void OnSetFileSecurityA() = 0;
		virtual void OnSetFileShortNameA() = 0;
		virtual void OnSetFileShortNameW() = 0;
		virtual void OnSetSearchPathMode() = 0;
		virtual void OnWriteEncryptedFileRaw() = 0;
	};
}
