#pragma once 

namespace Monitor
{
	export class IDetourCallback
	{
	public:
		virtual void OnShutdown() = 0;
		virtual void OnError(std::string_view message) = 0;

		// FileApi
		virtual void OnAreFileApisANSI() = 0;
		virtual void OnCompareFileTime() = 0;
		virtual void OnCreateDirectoryA() = 0;
		virtual void OnCreateDirectoryW() = 0;
		virtual void OnCreateFile2() = 0;
		virtual void OnCreateFileA() = 0;
		virtual void OnCreateFileW() = 0;
		virtual void OnDefineDosDeviceW() = 0;
		virtual void OnDeleteFileA() = 0;
		virtual void OnDeleteFileW() = 0;
		virtual void OnDeleteVolumeMountPointW() = 0;
		virtual void OnFileTimeToLocalFileTime() = 0;
		virtual void OnFindClose() = 0;
		virtual void OnFindCloseChangeNotification() = 0;
		virtual void OnFindFirstChangeNotificationA() = 0;
		virtual void OnFindFirstChangeNotificationW() = 0;
		virtual void OnFindFirstFileA() = 0;
		virtual void OnFindFirstFileW() = 0;
		virtual void OnFindFirstFileExA() = 0;
		virtual void OnFindFirstFileExW() = 0;
		virtual void OnFindFirstFileNameW() = 0;
		virtual void OnFindFirstStreamW() = 0;
		virtual void OnFindFirstVolumeW() = 0;
		virtual void OnFindNextChangeNotification() = 0;
		virtual void OnFindNextFileA() = 0;
		virtual void OnFindNextFileW() = 0;
		virtual void OnFindNextFileNameW() = 0;
		virtual void OnFindNextStreamW() = 0;
		virtual void OnFindNextVolumeW() = 0;
		virtual void OnFindVolumeClose() = 0;
		virtual void OnFlushFileBuffers() = 0;
		virtual void OnGetCompressedFileSizeA() = 0;
		virtual void OnGetCompressedFileSizeW() = 0;
		virtual void OnGetDiskFreeSpaceA() = 0;
		virtual void OnGetDiskFreeSpaceW() = 0;
		virtual void OnGetDiskFreeSpaceExA() = 0;
		virtual void OnGetDiskFreeSpaceExW() = 0;
		virtual void OnGetDriveTypeA() = 0;
		virtual void OnGetDriveTypeW() = 0;
		virtual void OnGetFileAttributesA() = 0;
		virtual void OnGetFileAttributesW() = 0;
		virtual void OnGetFileAttributesExA() = 0;
		virtual void OnGetFileAttributesExW() = 0;
		virtual void OnGetFileInformationByHandle() = 0;
		virtual void OnGetFileSize() = 0;
		virtual void OnGetFileSizeEx() = 0;
		virtual void OnGetFileTime() = 0;
		virtual void OnGetFileType() = 0;
		virtual void OnGetFinalPathNameByHandleA() = 0;
		virtual void OnGetFinalPathNameByHandleW() = 0;
		virtual void OnGetFullPathNameA() = 0;
		virtual void OnGetFullPathNameW() = 0;
		virtual void OnGetLogicalDrives() = 0;
		virtual void OnGetLogicalDriveStringsW() = 0;
		virtual void OnGetLongPathNameA() = 0;
		virtual void OnGetLongPathNameW() = 0;
		virtual void OnGetShortPathNameW() = 0;
		virtual void OnGetTempFileNameA() = 0;
		virtual void OnGetTempFileNameW() = 0;
		virtual void OnGetTempPathA() = 0;
		virtual void OnGetTempPathW() = 0;
		virtual void OnGetVolumeInformationA() = 0;
		virtual void OnGetVolumeInformationW() = 0;
		virtual void OnGetVolumeInformationByHandleW() = 0;
		virtual void OnGetVolumeNameForVolumeMountPointW() = 0;
		virtual void OnGetVolumePathNamesForVolumeNameW() = 0;
		virtual void OnGetVolumePathNameW() = 0;
		virtual void OnLocalFileTimeToFileTime() = 0;
		virtual void OnLockFile() = 0;
		virtual void OnLockFileEx() = 0;
		virtual void OnQueryDosDeviceW() = 0;
		virtual void OnReadFile() = 0;
		virtual void OnReadFileEx() = 0;
		virtual void OnReadFileScatter() = 0;
		virtual void OnRemoveDirectoryA() = 0;
		virtual void OnRemoveDirectoryW() = 0;
		virtual void OnSetEndOfFile() = 0;
		virtual void OnSetFileApisToANSI() = 0;
		virtual void OnSetFileApisToOEM() = 0;
		virtual void OnSetFileAttributesA() = 0;
		virtual void OnSetFileAttributesW() = 0;
		virtual void OnSetFileInformationByHandle() = 0;
		virtual void OnSetFileIoOverlappedRange() = 0;
		virtual void OnSetFilePointer() = 0;
		virtual void OnSetFilePointerEx() = 0;
		virtual void OnSetFileTime() = 0;
		virtual void OnSetFileValidData() = 0;
		virtual void OnUnlockFile() = 0;
		virtual void OnUnlockFileEx() = 0;
		virtual void OnWriteFile() = 0;
		virtual void OnWriteFileEx() = 0;
		virtual void OnWriteFileGather() = 0;

		// LibLoaderApi
		virtual void OnLoadLibraryA() = 0;
		virtual void OnLoadLibraryW() = 0;
		virtual void OnLoadLibraryExA() = 0;
		virtual void OnLoadLibraryExW() = 0;

		// ProcessEnv
		virtual void OnSearchPathA() = 0;
		virtual void OnSearchPathW() = 0;

		// ProcessThreadsApi
		virtual void OnCreateProcessA() = 0;
		virtual void OnCreateProcessW() = 0;
		virtual void OnCreateProcessAsUserA() = 0;
		virtual void OnCreateProcessAsUserW() = 0;
		virtual void OnExitProcess() = 0;

		// UndocumentedApi
		virtual void OnPrivCopyFileExA() = 0;
		virtual void OnPrivCopyFileExW() = 0;

		// WinBase
		virtual void OnCopyFileA() = 0;
		virtual void OnCopyFileW() = 0;
		virtual void OnCopyFile2() = 0;
		virtual void OnCopyFileExA() = 0;
		virtual void OnCopyFileExW() = 0;
		virtual void OnCopyFileTransactedA() = 0;
		virtual void OnCopyFileTransactedW() = 0;
		virtual void OnCreateDirectoryExA() = 0;
		virtual void OnCreateDirectoryExW() = 0;
		virtual void OnCreateDirectoryTransactedA() = 0;
		virtual void OnCreateDirectoryTransactedW() = 0;
		virtual void OnCreateFileTransactedA() = 0;
		virtual void OnCreateFileTransactedW() = 0;
		virtual void OnCreateHardLinkA() = 0;
		virtual void OnCreateHardLinkW() = 0;
		virtual void OnCreateHardLinkTransactedA() = 0;
		virtual void OnCreateHardLinkTransactedW() = 0;
		virtual void OnCreateProcessWithLogonW() = 0;
		virtual void OnCreateProcessWithTokenW() = 0;
		virtual void OnCreateSymbolicLinkA() = 0;
		virtual void OnCreateSymbolicLinkW() = 0;
		virtual void OnCreateSymbolicLinkTransactedA() = 0;
		virtual void OnCreateSymbolicLinkTransactedW() = 0;
		virtual void OnDecryptFileA() = 0;
		virtual void OnDecryptFileW() = 0;
		virtual void OnDeleteFileTransactedA() = 0;
		virtual void OnDeleteFileTransactedW() = 0;
		virtual void OnEncryptFileA() = 0;
		virtual void OnEncryptFileW() = 0;
		virtual void OnFileEncryptionStatusA() = 0;
		virtual void OnFileEncryptionStatusW() = 0;
		virtual void OnFindFirstFileNameTransactedW() = 0;
		virtual void OnFindFirstFileTransactedA() = 0;
		virtual void OnFindFirstFileTransactedW() = 0;
		virtual void OnFindFirstStreamTransactedW() = 0;
		virtual void OnGetBinaryTypeA() = 0;
		virtual void OnGetBinaryTypeW() = 0;
		virtual void OnGetCompressedFileSizeTransactedA() = 0;
		virtual void OnGetCompressedFileSizeTransactedW() = 0;
		virtual void OnGetDllDirectoryA() = 0;
		virtual void OnGetDllDirectoryW() = 0;
		virtual void OnGetFileAttributesTransactedA() = 0;
		virtual void OnGetFileAttributesTransactedW() = 0;
		virtual void OnGetFileBandwidthReservation() = 0;
		virtual void OnGetFileInformationByHandleEx() = 0;
		virtual void OnGetFileSecurityA() = 0;
		virtual void OnGetFullPathNameTransactedA() = 0;
		virtual void OnGetFullPathNameTransactedW() = 0;
		virtual void OnGetLongPathNameTransactedA() = 0;
		virtual void OnGetLongPathNameTransactedW() = 0;
		virtual void OnGetQueuedCompletionStatus() = 0;
		virtual void OnGetQueuedCompletionStatusEx() = 0;
		virtual void OnGetShortPathNameA() = 0;
		virtual void OnLoadModule() = 0;
		virtual void OnLoadPackagedLibrary() = 0;
		virtual void OnMoveFileA() = 0;
		virtual void OnMoveFileW() = 0;
		virtual void OnMoveFileExA() = 0;
		virtual void OnMoveFileExW() = 0;
		virtual void OnMoveFileTransactedA() = 0;
		virtual void OnMoveFileTransactedW() = 0;
		virtual void OnMoveFileWithProgressA() = 0;
		virtual void OnMoveFileWithProgressW() = 0;
		virtual void OnOpenEncryptedFileRawA() = 0;
		virtual void OnOpenEncryptedFileRawW() = 0;
		virtual void OnOpenFile() = 0;
		virtual void OnOpenFileById() = 0;
		virtual void OnReadEncryptedFileRaw() = 0;
		virtual void OnRemoveDirectoryTransactedA() = 0;
		virtual void OnRemoveDirectoryTransactedW() = 0;
		virtual void OnReOpenFile() = 0;
		virtual void OnReplaceFileA() = 0;
		virtual void OnReplaceFileW() = 0;
		virtual void OnSetCurrentDirectoryA() = 0;
		virtual void OnSetCurrentDirectoryW() = 0;
		virtual void OnSetDllDirectoryA() = 0;
		virtual void OnSetDllDirectoryW() = 0;
		virtual void OnSetFileAttributesTransactedA() = 0;
		virtual void OnSetFileAttributesTransactedW() = 0;
		virtual void OnSetFileBandwidthReservation() = 0;
		virtual void OnSetFileCompletionNotificationModes() = 0;
		virtual void OnSetFileSecurityA() = 0;
		virtual void OnSetFileShortNameA() = 0;
		virtual void OnSetFileShortNameW() = 0;
		virtual void OnSetSearchPathMode() = 0;
		virtual void OnWriteEncryptedFileRaw() = 0;
	};
}
