#!/bin/bash
echo "Linux Build!"

# Stop on first error
set -e

SCRIPTS_DIR=$(dirname "$0")

# Build Client
echo $SCRIPTS_DIR/linux-build-client
eval $SCRIPTS_DIR/linux-build-client

# Build SWhere tool
echo $SCRIPTS_DIR/linux-build-swhere
eval $SCRIPTS_DIR/linux-build-swhere

# Build PackageManager
echo $SCRIPTS_DIR/linux-build-packagemanager
eval $SCRIPTS_DIR/linux-build-packagemanager

# Build Generate
echo $SCRIPTS_DIR/linux-build-generate
eval $SCRIPTS_DIR/linux-build-generate