Name: "Soup.Api.Client"
Language: "C#|0.1"
Version: "1.0.0"
Source: [
	"Models/FileParameter.cs"
	"Models/FileResponse.cs"
	"Models/GenerateClosureRequestModel.cs"
	"Models/GenerateClosureResult.cs"
	"Models/GenerateClosureResultModel.cs"
	"Models/LanguageModel.cs"
	"Models/LanguageReferenceModel.cs"
	"Models/PackageCreateOrUpdateModel.cs"
	"Models/PackageLocalOrPublicExactReferenceModel.cs"
	"Models/PackageLocalOrPublicExactReferenceWithSubGraphsModel.cs"
	"Models/PackageLocalReferenceModel.cs"
	"Models/PackageModel.cs"
	"Models/PackagePublicExactReferenceModel.cs"
	"Models/PackagePublicReferenceModel.cs"
	"Models/PackageSummaryModel.cs"
	"Models/PackageVersionModel.cs"
	"Models/ProblemDetails.cs"
	"Models/SearchPackagesModel.cs"
	"Models/SemanticVersion.cs"
	"Models/SemanticVersionExactModel.cs"
	"Models/SemanticVersionModel.cs"
	"Models/SourceGenerationContext.cs"
	"ApiException.cs"
	"ClosureClient.cs"
	"LanguagesClient.cs"
	"PackagesClient.cs"
	"PackageVersionsClient.cs"
	"SearchClient.cs"
]
