#!/bin/bash
echo "Linux Build!"

BINDIR=/mnt/d/Repos/llvm-project/build-linux/bin
CXX=clang++
CXX_FLAGS="-DSOUP_BUILD -std=c++2a -fmodules-ts"

# Build Json11
mkdir -p ../Dependencies/Json11/out/obj/Clang/
eval $BINDIR/$CXX $CXX_FLAGS --precompile ../Dependencies/Json11/json11.cppm -o ../Dependencies/Json11/out/obj/Clang/json11.pcm
eval $BINDIR/$CXX $CXX_FLAGS -c ../Dependencies/Json11/out/obj/Clang/json11.pcm -o ../Dependencies/Json11/out/obj/Clang/json11.o

# Build Toml11
mkdir -p ../Dependencies/toml11/out/obj/Clang/
eval $BINDIR/$CXX $CXX_FLAGS --precompile ../Dependencies/toml11/toml.cppm -o ../Dependencies/toml11/out/obj/Clang/toml11.pcm
eval $BINDIR/$CXX $CXX_FLAGS -c ../Dependencies/toml11/out/obj/Clang/toml11.pcm -o ../Dependencies/toml11/out/obj/Clang/toml11.o
