Name: "Opal"
Language: "C#|0.1"
Version: "1.3.0"
Source: [
	"IO/IConsoleInputStream.cs"
	"IO/IConsoleManager.cs"
	"IO/MockConsoleInputStream.cs"
	"IO/MockConsoleManager.cs"
	# "IO/SystemConsoleInputStream.cs"
	# "IO/SystemConsoleManager.cs"
	"Logger/ConsoleTraceListener.cs"
	"Logger/EventTypeFilter.cs"
	"Logger/IEventFilter.cs"
	"Logger/Log.cs"
	"Logger/ScopedTraceListenerRegister.cs"
	"Logger/TestTraceListener.cs"
	# "Logger/TextWriterExtendedTraceListener.cs"
	"Logger/TraceListener.cs"
	"System/DirectoryEntry.cs"
	"System/IFileSystem.cs"
	"System/IInputFile.cs"
	"System/ILibrary.cs"
	"System/ILibraryManager.cs"
	"System/IOutputFile.cs"
	"System/IProcess.cs"
	"System/IProcessManager.cs"
	"System/MockFile.cs"
	"System/MockFileSystem.cs"
	"System/MockLibrary.cs"
	"System/MockLibraryManager.cs"
	"System/MockProcess.cs"
	"System/MockProcessManager.cs"
	"System/RuntimeProcess.cs"
	"System/RuntimeProcessManager.cs"
	# "System/STLFileSystem.cs"
	# "System/STLInputFile.cs"
	# "System/STLOutputFile.cs"
	# "System/WindowsDynamicLibrary.cs"
	# "System/WindowsDynamicLibraryManager.cs"
	"Utilities/LifetimeManager.cs"
	"Utilities/Path.cs"
	"Utilities/ScopedSingleton.cs"
	"Utilities/SemanticVersion.cs"
]
